#! /bin/sh
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &
killall -q polybar > /dev/null
polybar bspwmbar &
#pgrep -x picom > /dev/null || picom -b &

feh --bg-center ~/.config/wallpaper.jpg

bspc monitor DP1 -d web editor term 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config top_padding         37
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0

bspc config single_monocle       false
bspc config click_to_focus       none
bspc config focus_follows_pointer true

bspc config remove_disabled_monitors      true

bspc config pointer_modifier shift
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config remove_disabled_monitors      true
bspc config remove_unplugged_monitors     true
bspc config merge_overlapping_monitors    true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^1' follow=on
bspc rule -a Spotify desktop='^10' follow=on
