#!/bin/sh

SINK=0

volume=$(pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')
mute=$(pactl list sinks | grep '^[[:space:]]Mute:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's/[[:blank:]]Mute: //')

if [[ $mute == "yes" ]]; then
    echo ""
else
    echo "$volume"
fi
