[font]
size = 12.0

[font.normal]
family = "Droid Sans Mono"

[[keyboard.bindings]]
chars = "\u0001n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0001p"
key = "Tab"
mods = "Shift|Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 50000
